name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Installation de Node et compilation des assets (Vite) sur GitHub
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies & Build
        run: |
          cd ping-ouistreham
          npm install
          npm run build

      # 2. Envoi du dossier 'build' compilé vers Hostinger via SCP
      - name: Upload Build Assets
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          source: "ping-ouistreham/public/build/"
          target: "domains/tournoi-de-oustreham.skopee.fr/public_html/ping-ouistreham/public/"
          strip_components: 2 # Enlève 'ping-ouistreham/public/' du chemin source pour ne transférer que 'build'

      # 3. Exécution des commandes PHP sur le serveur Hostinger via SSH
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          script: |
            cd domains/tournoi-de-oustreham.skopee.fr/public_html
            git pull origin main
            
            # Entrer dans le dossier de l'application pour les commandes Laravel
            cd ping-ouistreham
            
            # Installation des dépendances PHP
            composer install --no-dev --optimize-autoloader
            
            # Mise à jour de la base de données et vidage des caches
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache