name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Compilation des assets sur GitHub (car npm ne marche pas sur Hostinger)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies & Build
        run: |
          cd ping-ouistreham
          npm install
          npm run build

      # 2. Envoi du dossier 'build' vers Hostinger
      - name: Upload Build Assets
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          source: "ping-ouistreham/public/build/"
          target: "domains/tournoi-de-oustreham.skopee.fr/public_html/ping-ouistreham/public/"
          strip_components: 2

      # 3. Mise à jour du code PHP via SSH
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          script: |
            cd domains/tournoi-de-oustreham.skopee.fr/public_html
            git pull origin main
            
            # Entrée dans le dossier Laravel
            cd ping-ouistreham
            
            # Installation PHP et mise à jour Laravel
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache