name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM & Build
        run: |
          cd ping-ouistreham
          npm install
          npm run build

      - name: Upload Build Assets
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          # On envoie le dossier build local vers le dossier public du serveur
          source: "ping-ouistreham/public/build/"
          target: "domains/tournoi-de-ouistreham.skopee.fr/public_html/ping-ouistreham/public/"
          strip_components: 2

      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          script: |
            # 1. Aller à la racine du domaine (avec le 'i')
            cd domains/tournoi-de-ouistreham.skopee.fr/public_html
            
            # 2. Nettoyer les fichiers locaux pour éviter les conflits Git
            git reset --hard HEAD
            git pull origin main
            
            # 3. Entrer dans le dossier de l'application
            cd ping-ouistreham

            # 4. Installation des dépendances PHP
            composer install --no-dev --optimize-autoloader

            # 5. Mise à jour de la base de données et vidage des caches
            # Le flag --force est nécessaire en production
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache